- id: readability
  name: readability
  description: Check documentation readability metrics
  entry: readability --check --format diagnostic
  language: golang
  files: \.md$
  pass_filenames: true
  types: [markdown]

- id: readability-docs
  name: readability (docs only)
  description: Check documentation readability metrics for docs/ directory
  entry: readability --check --format diagnostic docs/
  language: golang
  files: ^docs/.*\.md$
  pass_filenames: false
  types: [markdown]
