# yaml-language-server: $schema=./docs/schemas/config.json
# Readability configuration for this repository's documentation
# These thresholds ensure docs are accessible to newcomers
---
thresholds:
  # Grade level: Target high school reading level (grades 10-12)
  max_grade: 14
  max_ari: 14

  # Flesch Reading Ease: 30+ is "difficult but accessible"
  min_ease: 30

  # Gunning Fog: 12-14 is ideal for technical documentation
  max_fog: 16

  # Structure limits
  max_lines: 400

  # Require at least one admonition per page for visual breaks
  min_admonitions: 1

  # No mid-sentence dashes allowed (prevents AI slop)
  max_dash_density: 0

# Path-specific overrides
overrides:
  # Metrics documentation explains technical formulas and legitimately needs higher complexity
  - path: docs/metrics/
    thresholds:
      max_grade: 15
      max_ari: 17

  # Docker docs cover advanced security topics (Cosign, SBOM, distroless) requiring technical language
  - path: docs/getting-started/docker.md
    thresholds:
      max_grade: 16
      max_ari: 19
      max_fog: 18

  # Developer manual: Implementation planning docs for contributors with technical depth
  - path: docs/developer-manual/
    thresholds:
      max_grade: 30          # Allow complex technical writing
      max_ari: 35            # Detailed analysis and code examples
      max_fog: 26            # Architecture discussions require precision
      min_ease: -100         # Disable reading ease (technical content)
      max_lines: 800         # Comprehensive documentation needs space
      min_admonitions: -1    # Not required for technical specs
      max_dash_density: 150  # Allow parenthetical constructions for clarity
