name: 'Readability'
description: 'Analyze documentation readability and content quality metrics'
author: 'Adaptive Enforcement Lab'

branding:
  icon: 'book-open'
  color: 'blue'

inputs:
  path:
    description: 'Path to analyze (file or directory)'
    required: false
    default: 'docs/'
  format:
    description: 'Output format (table, markdown, json, summary, report)'
    required: false
    default: 'markdown'
  config:
    description: 'Path to config file'
    required: false
    default: ''
  check:
    description: 'Enable check mode (fail on threshold violations)'
    required: false
    default: 'false'
  max-grade:
    description: 'Maximum Flesch-Kincaid grade level'
    required: false
    default: ''
  max-ari:
    description: 'Maximum ARI score'
    required: false
    default: ''
  max-lines:
    description: 'Maximum lines per file'
    required: false
    default: ''

outputs:
  report:
    description: 'Analysis report in specified format'
  passed:
    description: 'Whether all thresholds were met (true/false)'
  files-analyzed:
    description: 'Number of files analyzed'

runs:
  using: 'composite'
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache: false

    - name: Build readability
      shell: bash
      run: |
        cd ${{ github.action_path }}
        go build -o readability ./cmd/readability

    - name: Run analysis
      id: analyze
      shell: bash
      run: |
        ARGS=""

        if [ -n "${{ inputs.config }}" ]; then
          ARGS="$ARGS --config ${{ inputs.config }}"
        fi

        ARGS="$ARGS --format ${{ inputs.format }}"

        if [ "${{ inputs.check }}" = "true" ]; then
          ARGS="$ARGS --check"
        fi

        if [ -n "${{ inputs.max-grade }}" ]; then
          ARGS="$ARGS --max-grade ${{ inputs.max-grade }}"
        fi

        if [ -n "${{ inputs.max-ari }}" ]; then
          ARGS="$ARGS --max-ari ${{ inputs.max-ari }}"
        fi

        if [ -n "${{ inputs.max-lines }}" ]; then
          ARGS="$ARGS --max-lines ${{ inputs.max-lines }}"
        fi

        ${{ github.action_path }}/readability $ARGS ${{ inputs.path }}
